// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BigQuicHelper
void BigQuicHelper(std::vector<std::string> argvPasser);
RcppExport SEXP BigQuic_BigQuicHelper(SEXP argvPasserSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type argvPasser(argvPasserSEXP);
    BigQuicHelper(argvPasser);
    return R_NilValue;
END_RCPP
}
